import { Vehicle } from "@/types";

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: "veh_titan_fiat500",
    companyId: "titan_car",
    brand: "Fiat",
    model: "500 Hybrid",
    version: "1.0 70ch Dolcevita",
    year: 2024,
    mileage: 5400,
    fuelType: "Essence",
    transmission: "Manuelle",
    engine: "1.0L Hybrid 70ch",
    power: 70,
    fiscalPower: 4,
    doors: 3,
    seats: 4,
    bodyType: "Citadine",
    rentalCategory: "Économique",
    color: "Vert Menthe Dolcevita",
    interiorColor: "Ivoire & Tissu Éco-Cuir Dolcevita",
    condition: "Neuf",
    dailyRate: 5000,
    deposit: 35000,
    minRentalDays: 2,
    price: 3800000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Blida / Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "La nouvelle Fiat 500 Hybrid Dolcevita. Citadine chic, agilissime et ultra-économe pour vos déplacements quotidiens. Écran tactile Uconnect 7'' avec Apple CarPlay et Android Auto, toit panoramique en verre, finition haut de gamme et confort urbain absolu.",
    mainImage: "/vehicles/fiat500.jpg",
    gallery: [
      "/vehicles/fiat500.jpg"
    ],
    features: [
      "Motorisation Hybride 1.0L 70ch ultra-économique",
      "Écran tactile Uconnect 7'' avec Apple CarPlay & Android Auto",
      "Toit panoramique en verre fixe avec store occultant",
      "Mode City avec direction assistée ultra-douce",
      "Livraison 24/7 à l'Aéroport d'Alger Houari Boumediene"
    ],
    featured: true,
    publishedAt: "2026-08-22T07:50:00Z",
    updatedAt: "2026-08-22T07:50:00Z",
  },
  {
    id: "veh_titan_gclass",
    companyId: "titan_car",
    brand: "Mercedes-Benz",
    model: "Classe G 63 AMG",
    version: "4.0 V8 BiTurbo 585ch Night Package",
    year: 2024,
    mileage: 6500,
    fuelType: "Essence",
    transmission: "Automatique",
    engine: "4.0L V8 BiTurbo AMG",
    power: 585,
    fiscalPower: 24,
    doors: 5,
    seats: 5,
    bodyType: "SUV / 4x4",
    rentalCategory: "Prestige & SUV VIP",
    color: "Noir Obsidian Métallisé",
    interiorColor: "Cuir Nappa Rouge Designo & Carbone",
    condition: "Neuf",
    dailyRate: 45000,
    deposit: 200000,
    minRentalDays: 1,
    price: 38000000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Aéroport d'Alger / Boufarik / Service VIP",
    availableLocations: ["Aéroport Alger Houari Boumediene", "Boufarik Showroom", "Service Chauffeur VIP Alger"],
    description: "L'incontournable Mercedes-Benz Classe G 63 AMG. Son d'échappement V8 BiTurbo légendaire, habitacle cuir Nappa rouge, double écran Widescreen, suspension pilotée AMG Ride Control et présence inégalée sur la route. Disponible à la réservation avec livraison 24/7 à l'Aéroport d'Alger.",
    mainImage: "/vehicles/gclass.jpg",
    gallery: [
      "/vehicles/gclass.jpg"
    ],
    features: [
      "Moteur V8 BiTurbo 585ch avec sonorité AMG commutable",
      "Livraison VIP 24/7 à l'Aéroport d'Alger Houari Boumediene",
      "Système Audio Burmester® 3D Surround Sound",
      "Sièges réglables avec mémoire, massage et ventilation",
      "Pack Night AMG avec jantes forgées 22 pouces",
      "Option chauffeur privé ou conduite libre"
    ],
    featured: true,
    publishedAt: "2026-08-15T10:00:00Z",
    updatedAt: "2026-08-21T10:00:00Z",
  },
  {
    id: "veh_titan_coolray",
    companyId: "titan_car",
    brand: "Geely",
    model: "Coolray S",
    version: "1.5L Turbo 177ch Sport Edition",
    year: 2024,
    mileage: 8200,
    fuelType: "Essence",
    transmission: "Automatique",
    engine: "1.5L Turbo GDI 177ch",
    power: 177,
    fiscalPower: 9,
    doors: 5,
    seats: 5,
    bodyType: "Crossover / SUV",
    rentalCategory: "SUV & Crossover",
    color: "Gris Céleste / Toit Noir",
    interiorColor: "Cuir Bicolore Rouge & Noir Sport",
    condition: "Neuf",
    dailyRate: 12500,
    deposit: 60000,
    minRentalDays: 2,
    price: 5800000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Blida / Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Crossover compact de prestige Geely Coolray S Sport Edition en finition Gris Céleste avec toit noir et calandre sport red-accented. Équipé d'une boîte automatique 7 rapports, double écran numérique panoramique, toit ouvrant panoramique et caméras 360°.",
    mainImage: "/vehicles/coolray.jpg",
    gallery: [
      "/vehicles/coolray.jpg"
    ],
    features: [
      "Motorisation 1.5L Turbo 177ch et boîte automatique DCT-7",
      "Pack Sport avec calandre tressée et liseré rouge d'origine",
      "Écran panoramique tactile avec Apple CarPlay & Android Auto",
      "Toit panoramique ouvrant électrique",
      "Caméras de recul 360° et aide au stationnement intelligente",
      "Livraison 24/7 à l'Aéroport d'Alger Houari Boumediene"
    ],
    featured: true,
    publishedAt: "2026-08-18T10:00:00Z",
    updatedAt: "2026-08-22T08:00:00Z",
  },
  {
    id: "veh_titan_golf8",
    companyId: "titan_car",
    brand: "Volkswagen",
    model: "Golf 8",
    version: "2.0 TDI 150ch DSG7 R-Line",
    year: 2024,
    mileage: 12500,
    fuelType: "Diesel",
    transmission: "Automatique",
    engine: "2.0L TDI Turbo Diesel",
    power: 150,
    fiscalPower: 8,
    doors: 5,
    seats: 5,
    bodyType: "Berline",
    rentalCategory: "Berline Confort",
    color: "Gris Nardo",
    interiorColor: "Noir / Sièges Sport R-Line",
    condition: "Neuf",
    dailyRate: 9500,
    deposit: 50000,
    minRentalDays: 2,
    price: 6900000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Aéroport d'Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Volkswagen Golf 8 R-Line en boîte automatique DSG7. Idéale pour vos déplacements d'affaires ou séjours à Alger et Blida. GPS intégré, Digital Cockpit, climatisation tri-zone et confort haut de gamme. Véhicule nettoyé et désinfecté avant chaque remise des clés.",
    mainImage: "/vehicles/golf8.jpg",
    gallery: [
      "/vehicles/golf8.jpg"
    ],
    features: [
      "Boîte automatique DSG 7 rapports",
      "Livraison possible Aéroport d'Alger Houari Boumediene 24/7",
      "Digital Cockpit & Navigation GPS intégrée",
      "Apple CarPlay & Android Auto sans fil",
      "Climatisation automatique régulée",
      "Assistance routière 24h/24 & 7j/7 incluse"
    ],
    featured: true,
    publishedAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
  },
  {
    id: "veh_titan_tucson",
    companyId: "titan_car",
    brand: "Hyundai",
    model: "Tucson",
    version: "1.6 CRDi 136ch DCT-7 N-Line 4WD",
    year: 2024,
    mileage: 18000,
    fuelType: "Diesel",
    transmission: "Automatique",
    engine: "1.6L Turbo Diesel Smartstream",
    power: 136,
    fiscalPower: 7,
    doors: 5,
    seats: 5,
    bodyType: "SUV / 4x4",
    rentalCategory: "SUV & 4x4",
    color: "Noir Intense (Showroom)",
    interiorColor: "Cuir & Alcantara Noir",
    condition: "Neuf",
    dailyRate: 13500,
    deposit: 60000,
    minRentalDays: 2,
    price: 7500000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Blida / Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "SUV de prestige Hyundai Tucson N-Line 4WD en finition Noir Intense. Espace généreux, coffre volumineux pour valises familiales, toit panoramique ouvrant, caméras 360° et boîte automatique pour une conduite souple sur l'autoroute.",
    mainImage: "/vehicles/tucson.jpg",
    gallery: [
      "/vehicles/tucson.jpg"
    ],
    features: [
      "Transmission intégrale 4WD et boîte automatique DCT-7",
      "Grand volume de coffre (parfait transferts aéroport)",
      "Double écran tactile et système audio premium",
      "Toit ouvrant panoramique électrique",
      "Prise en charge à l'Aéroport d'Alger avec panneau nominatif"
    ],
    featured: true,
    publishedAt: "2026-08-08T09:00:00Z",
    updatedAt: "2026-08-21T08:00:00Z",
  },
  {
    id: "veh_titan_clio5",
    companyId: "titan_car",
    brand: "Renault",
    model: "Clio 5",
    version: "1.5 dCi 115ch Intens",
    year: 2024,
    mileage: 15400,
    fuelType: "Diesel",
    transmission: "Manuelle",
    engine: "1.5L Blue dCi Diesel",
    power: 115,
    fiscalPower: 5,
    doors: 5,
    seats: 5,
    bodyType: "Citadine",
    rentalCategory: "Compacte",
    color: "Bleu Céladon",
    interiorColor: "Noir et inserts chrome",
    condition: "Neuf",
    dailyRate: 5500,
    deposit: 35000,
    minRentalDays: 2,
    price: 4300000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Blida",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Renault Clio 5 nouvelle génération motorisation diesel 115ch avec finition Intens. Conduite feutrée et ultra-silencieuse, cockpit digital, écran tactile Easy Link 7 pouces avec navigation et aide au stationnement.",
    mainImage: "/vehicles/clio5.jpg",
    gallery: [
      "/vehicles/clio5.jpg"
    ],
    features: [
      "Moteur diesel 1.5 Blue dCi sobre et endurant",
      "Écran Easy Link avec Apple CarPlay / Android Auto",
      "Feux Full LED Pure Vision",
      "Radar de recul et capteurs de distance",
      "Carte mains-libres démarrage sans clé"
    ],
    featured: true,
    publishedAt: "2026-08-12T11:00:00Z",
    updatedAt: "2026-08-20T16:00:00Z",
  },
  {
    id: "veh_titan_octavia",
    companyId: "titan_car",
    brand: "Skoda",
    model: "Octavia",
    version: "2.0 TDI 150ch DSG7 Style",
    year: 2024,
    mileage: 9800,
    fuelType: "Diesel",
    transmission: "Automatique",
    engine: "2.0L Turbo Diesel",
    power: 150,
    fiscalPower: 8,
    doors: 5,
    seats: 5,
    bodyType: "Berline",
    rentalCategory: "Berline Confort",
    color: "Noir Magic Nacré",
    interiorColor: "Cuir Noir / Finition Chrome",
    condition: "Neuf",
    dailyRate: 11000,
    deposit: 55000,
    minRentalDays: 2,
    price: 7200000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Grande berline routière par excellence. Coffre immense de 600 litres pour tous vos bagages, boîte automatique DSG ultra fluide, phares Matrix LED et insonorisation digne des segments supérieurs.",
    mainImage: "/vehicles/octavia.jpg",
    gallery: [
      "/vehicles/octavia.jpg"
    ],
    features: [
      "Boîte automatique DSG 7 rapports",
      "Coffre gigantesque de 600 litres",
      "Projecteurs Full Matrix LED adaptatifs",
      "Cockpit digital et écran central 10 pouces",
      "Idéal pour délégations d'affaires et réceptions"
    ],
    featured: true,
    publishedAt: "2026-08-01T09:00:00Z",
    updatedAt: "2026-08-20T17:00:00Z",
  },
  {
    id: "veh_titan_sportage",
    companyId: "titan_car",
    brand: "Kia",
    model: "Sportage",
    version: "1.6 T-GDi 150ch DCT7 GT-Line",
    year: 2024,
    mileage: 11200,
    fuelType: "Essence",
    transmission: "Automatique",
    engine: "1.6L Turbo Essence Smartstream",
    power: 150,
    fiscalPower: 8,
    doors: 5,
    seats: 5,
    bodyType: "SUV / 4x4",
    rentalCategory: "SUV & 4x4",
    color: "Gris Acier",
    interiorColor: "Cuir & Suédine Noire GT-Line",
    condition: "Neuf",
    dailyRate: 14000,
    deposit: 65000,
    minRentalDays: 2,
    price: 7800000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Aéroport d'Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Le nouveau Kia Sportage 5ème génération GT-Line allie audace stylistique et grand luxe à bord. Double écran incurvé futuriste, toit ouvrant, caméras 360 et sécurité active de pointe.",
    mainImage: "/vehicles/sportage.jpg",
    gallery: [
      "/vehicles/sportage.jpg"
    ],
    features: [
      "Double écran panoramique incurvé 2x 12.3 pouces",
      "Finition sportive GT-Line extérieure et intérieure",
      "Boîte automatique séquentielle DCT-7",
      "Toit ouvrant panoramique électrique",
      "Livraison directe VIP à l'Aéroport International d'Alger"
    ],
    featured: true,
    publishedAt: "2026-08-11T09:00:00Z",
    updatedAt: "2026-08-21T08:00:00Z",
  },
  {
    id: "veh_em_03",
    companyId: "titan_car",
    brand: "Dacia",
    model: "Sandero Stepway",
    version: "1.0 TCe 90ch Expression",
    year: 2024,
    mileage: 7200,
    fuelType: "Essence",
    transmission: "Manuelle",
    engine: "1.0L Turbo TCe 90ch",
    power: 90,
    fiscalPower: 5,
    doors: 5,
    seats: 5,
    bodyType: "Crossover / Citadine",
    rentalCategory: "Économique & Crossover",
    color: "Gris Kaki Studio",
    interiorColor: "Tissu Stepway avec inserts Orange Cuivré",
    condition: "Neuf",
    dailyRate: 5500,
    deposit: 35000,
    minRentalDays: 2,
    price: 3900000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik / Blida / Alger",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Nouvelle Dacia Sandero Stepway Expression 2024. Crossover polyvalent, surélevé avec barres de toit modulables, écran Media Display 8'' Apple CarPlay & Android Auto, radars de recul et grand confort pour les routes urbaines et autoroutes d'Algérie.",
    mainImage: "/vehicles/dacia_sandero.jpg",
    gallery: [
      "/vehicles/dacia_sandero.jpg"
    ],
    features: [
      "Motorisation 1.0 Turbo TCe 90ch ultra-sobre",
      "Garde au sol surélevée & Look Crossover Stepway",
      "Écran Media Display 8'' avec réplication smartphone",
      "Barres de toit modulables d'origine",
      "Livraison 24/7 à l'Aéroport d'Alger Houari Boumediene"
    ],
    featured: true,
    publishedAt: "2026-08-22T08:50:00Z",
    updatedAt: "2026-08-22T08:50:00Z",
  },
  {
    id: "veh_titan_ibiza",
    companyId: "titan_car",
    brand: "Seat",
    model: "Ibiza",
    version: "1.6 MPI 110ch Highline",
    year: 2023,
    mileage: 26000,
    fuelType: "Essence",
    transmission: "Manuelle",
    engine: "1.6L Essence 4 cylindres",
    power: 110,
    fiscalPower: 6,
    doors: 5,
    seats: 5,
    bodyType: "Citadine",
    rentalCategory: "Économique",
    color: "Gris Magnétique",
    interiorColor: "Tissu Gris Anthracite",
    condition: "Très bon",
    dailyRate: 4800,
    deposit: 35000,
    minRentalDays: 2,
    price: 3600000,
    currency: "DZD",
    status: "AVAILABLE",
    location: "Boufarik",
    availableLocations: ["Boufarik Showroom", "Blida Centre", "Aéroport Alger Houari Boumediene"],
    description: "Seat Ibiza Highline économique, agile et fiable pour tous vos trajets urbains et régionaux entre Boufarik, Blida et la capitale Alger. Faible consommation, climatisation puissante et Bluetooth.",
    mainImage: "/vehicles/ibiza.jpg",
    gallery: [
      "/vehicles/ibiza.jpg"
    ],
    features: [
      "Tarif économique très compétitif",
      "Climatisation automatique bi-zone",
      "Écran tactile multimédia avec Bluetooth audio",
      "Régulateur et limiteur de vitesse",
      "Jantes alliage 16 pouces"
    ],
    featured: false,
    publishedAt: "2026-08-05T08:30:00Z",
    updatedAt: "2026-08-19T10:00:00Z",
  }
];
