import { Review, FaqItem, Lead, Customer, Appointment, RentalBooking } from "@/types";

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev_em_1",
    companyId: "el_moussafir",
    authorName: "Khaled B.",
    rating: 5,
    date: "2024-02-18",
    comment: "Service impeccable à Boufarik ! J'ai loué la Golf 8 R-Line pour 5 jours avec prise en charge directe à l'Aéroport d'Alger Houari Boumediene. Voiture très propre, formalités ultra rapides en 5 minutes. Je recommande sans hésitation.",
    verifiedPurchase: true,
    vehicleModel: "Volkswagen Golf 8 R-Line",
  },
  {
    id: "rev_em_2",
    companyId: "el_moussafir",
    authorName: "Samir Medjdoub",
    rating: 5,
    date: "2024-02-04",
    comment: "Très bonne agence de location à Boufarik / Blida. Véhicule Hyundai Tucson en parfait état, boîte automatique super agréable sur l'autoroute. Personnel sérieux et ponctuel pour le retour.",
    verifiedPurchase: true,
    vehicleModel: "Hyundai Tucson N-Line 4WD",
  },
  {
    id: "rev_em_3",
    companyId: "el_moussafir",
    authorName: "Amina Khelil",
    rating: 4,
    date: "2024-01-22",
    comment: "Excellente expérience pour un déplacement professionnel à Alger. La Clio 5 était économique et très propre. Tarifs clairs sans frais cachés.",
    verifiedPurchase: true,
    vehicleModel: "Renault Clio 5 Intens",
  },
  {
    id: "rev_em_4",
    companyId: "el_moussafir",
    authorName: "Mohamed Tariq",
    rating: 5,
    date: "2023-12-30",
    comment: "Chauffeur à l'heure à l'aéroport avec pancarte. Contrat clair et caution restituée sans aucun problème. Meilleure agence de location de la wilaya de Blida.",
    verifiedPurchase: true,
    vehicleModel: "Skoda Octavia Style DSG7",
  },
  {
    id: "rev_em_5",
    companyId: "el_moussafir",
    authorName: "Reda Bensalem",
    rating: 5,
    date: "2023-12-15",
    comment: "Réservation sur WhatsApp en 2 minutes. La Dacia Stepway automatique était parfaite pour un voyage en famille vers Tipaza et Blida. 5 étoiles méritées.",
    verifiedPurchase: true,
    vehicleModel: "Dacia Sandero Stepway Techroad",
  },
  {
    id: "rev_em_6",
    companyId: "el_moussafir",
    authorName: "Yassine Zeroual",
    rating: 4,
    date: "2023-11-28",
    comment: "Bonne prise en charge à l'agence de Boufarik. Véhicule bien révisé, climatisation puissante. Très bon rapport qualité prix.",
    verifiedPurchase: true,
    vehicleModel: "Seat Ibiza Highline",
  },
];

export const INITIAL_FAQS: FaqItem[] = [
  {
    id: "faq_em_1",
    category: "PURCHASE",
    question: "Quelles sont les conditions et documents requis pour louer une voiture chez EL MOUSSAFIR CARS ?",
    answer: "Pour louer un véhicule, il vous suffit de présenter : un permis de conduire valide (minimum 2 ans d'ancienneté ou selon catégorie), une pièce d'identité biométrique (CNI ou passeport pour les résidents à l'étranger), et un dépôt de caution (en espèces ou empreinte bancaire) restitué intégralement lors de la restitution du véhicule.",
  },
  {
    id: "faq_em_2",
    category: "SERVICES",
    question: "Assurez-vous la livraison et la récupération à l'Aéroport International d'Alger Houari Boumediene ?",
    answer: "Oui ! Nous assurons un service de navette et livraison directe 24h/24 et 7j/7 à l'Aéroport International d'Alger (Terminaux 1, 2 et Ouest). Notre agent vous accueille à la sortie des vols avec une pancarte à votre nom pour la remise immédiate des clés.",
  },
  {
    id: "faq_em_3",
    category: "SERVICES",
    question: "Puis-je réserver en ligne ou via WhatsApp sans avance obligatoire ?",
    answer: "Absolument. Vous pouvez bloquer votre véhicule en quelques secondes via notre plateforme ou directement sur WhatsApp. Vous recevez un récapitulatif officiel avec confirmation instantanée de la disponibilité.",
  },
  {
    id: "faq_em_4",
    category: "DOCUMENTS",
    question: "Quel est le montant de la caution (garantie) et comment est-elle restituée ?",
    answer: "Le montant de la caution varie entre 35 000 DA (citadines économiques) et 65 000 DA (grands SUV et berlines premium). Elle est restituée immédiatement dès le contrôle d'état des lieux au retour du véhicule.",
  },
  {
    id: "faq_em_5",
    category: "IMPORT_FINANCING",
    question: "Proposez-vous la location avec chauffeur ou la location longue durée (LLD) pour entreprises ?",
    answer: "Oui, EL MOUSSAFIR CARS dispose d'un service chauffeur privé VIP pour vos cérémonies et délégations, ainsi que d'offres de location moyenne et longue durée avec facturation entreprise officielle pour les sociétés à Boufarik, Blida et Alger.",
  },
];

export const INITIAL_RENTAL_BOOKINGS: RentalBooking[] = [
  {
    id: "book_em_01",
    companyId: "el_moussafir",
    vehicleId: "veh_em_01",
    vehicleTitle: "Volkswagen Golf 8 2.0 TDI DSG7 R-Line",
    vehicleImage: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80",
    customerName: "Karim Djebbar",
    phone: "0555123456",
    email: "karim.djebbar@gmail.com",
    startDate: "2026-08-25",
    startTime: "10:00",
    endDate: "2026-08-29",
    endTime: "18:00",
    days: 4,
    dailyRate: 9500,
    totalPrice: 38000,
    depositAmount: 50000,
    pickupLocation: "Aéroport Alger Houari Boumediene",
    returnLocation: "Aéroport Alger Houari Boumediene",
    options: {
      insuranceComprehensive: true,
      additionalDriver: false,
      babySeat: false,
      gpsNavigation: true,
      airportMeetAndGreet: true,
    },
    notes: "Vol AH1002 arrivée 09h30 Terminal Ouest",
    status: "CONFIRMED",
    source: "website_booking",
    campaign: "tiktok_summer",
    createdAt: "2026-08-20T14:00:00Z",
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead_demo_1",
    companyId: "el_moussafir",
    fullName: "Yacine Rahmani",
    phone: "0550123456",
    email: "yacine.rahmani@email.dz",
    vehicleId: "veh_em_01",
    vehicleTitle: "Volkswagen Golf 8 (2024) - R-Line Automatique",
    inquiryType: "AVAILABILITY",
    message: "Bonjour, j'arrive à l'aéroport d'Alger samedi prochain. Le véhicule est-il disponible pour 4 jours ?",
    preferredContact: "WHATSAPP",
    source: "website_fleet",
    campaign: "organic_direct",
    status: "QUALIFIED",
    notes: [
      {
        id: "note_1",
        author: "Agent EL MOUSSAFIR",
        text: "Client confirmé pour prise en charge aéroport samedi 10h. Voiture réservée.",
        createdAt: "2026-08-20T09:30:00Z",
      },
    ],
    createdAt: "2026-08-20T09:15:00Z",
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "cust_1",
    companyId: "el_moussafir",
    fullName: "Yacine Rahmani",
    phone: "0550123456",
    whatsapp: "+213550123456",
    email: "yacine.rahmani@email.dz",
    notes: "Client régulier - Préfère boîte automatique avec livraison Aéroport Alger",
    firstContactAt: "2024-01-10T14:00:00Z",
    lastContactAt: "2026-08-20T09:30:00Z",
    totalInquiries: 3,
    status: "CUSTOMER",
  },
  {
    id: "cust_2",
    companyId: "el_moussafir",
    fullName: "Farid Belkacemi",
    phone: "0770987654",
    whatsapp: "+213770987654",
    email: "farid.b@gmail.com",
    notes: "Location d'un Hyundai Tucson pour vacances en famille",
    firstContactAt: "2024-02-05T11:00:00Z",
    lastContactAt: "2024-02-18T16:00:00Z",
    totalInquiries: 2,
    status: "CUSTOMER",
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: "apt_1",
    companyId: "el_moussafir",
    customerName: "Karim Djebbar",
    phone: "0555123456",
    email: "karim.djebbar@gmail.com",
    vehicleId: "veh_em_01",
    vehicleTitle: "Volkswagen Golf 8 R-Line",
    date: "2026-08-25",
    timeSlot: "10:00 - 11:00",
    type: "SHOWROOM_VISIT",
    status: "CONFIRMED",
    notes: "Prise en charge et remise des clés à l'Aéroport d'Alger",
    createdAt: "2026-08-20T14:00:00Z",
  },
];
